language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
install:
- if [ "$CXX" = "g++" ]; then export CXX=g++-7; fi
- if [ "$CC" = "gcc" ]; then export CC=gcc-7; fi
before_script:
script:
- mkdir cmake-build-release
- cd cmake-build-release
- cmake ..
- cmake --build . --target all
before_deploy:
- cmake --build . --target install
- cmake --build . --target create_zip
deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  skip_cleanup: true
  file: test_game.zip
  on:
    tags: true
